version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: php-fpm.docker
    environment:
      PHP_IDE_CONFIG: serverName=page-analyzer
    volumes:
      - .:/app
    depends_on:
      - db
  php-cli:
    build:
      context: ./docker/php
      dockerfile: php-cli.docker
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: page_analyzer
      POSTGRES_PASSWORD: 123qwe
    ports:
      - "5432:5432"
  node-watch:
    build:
      context: ./docker/node
    volumes:
      - .:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  node-cli:
    build:
      context: ./docker/node
    volumes:
      - .:/app
volumes:
  db:
